app:
    name: '@pom.artifactId@'
    version: '@pom.version@'
info:
    version: '@pom.version@'

springfox:
    documentation:
        swagger:
            v2:
                path: /swagger.json
 
server:
     port: EXAMPLE --> 8090
silcam:
     portal:
         ciudado:
              url: EXAMPLE --> http://localhost:3000
         bpm:
              url: EXAMPLE --> http://localhost:8080
     security:
         jwt:
              key: EXAMPLE --> 123456abcdef
spring:
     data:
         mongodb:
              uri: EXAMPLE --> mongodb://localhost:27017/mongo
     datasource:
         url: EXAMPLE --> jdbc:postgresql://localhost:5432/jdbc
         username: EXAMPLE --> postgres
         password: EXAMPLE --> postgres
     jpa:
         hibernate:
              ddl-auto: validate
         properties:
              hibernate:
                  enable_lazy_load_no_trans: true
     mail:
         host: EXAMPLE --> smt.host.com
         port: EXAMPLE --> 25
         user: EXAMPLE --> user
         password: EXAMPLE --> password
         protocol: smtp
         tls: false
         auth: false
         from: EXAMPLE --> no-reply@silcam.com
security:
    wso2:
        enabled: EXAMPLE --> false
    basic:
        enabled: EXAMPLE --> false
management:
    security:
        enabled: EXAMPLE --> false
logging:
    level:
        org:
           hibernate:
               SQL: debug
               type:
                   descriptor:
                       sql:
                          BasicBinder: TRACE