app:
    name: '@pom.artifactId@'
    version: '@pom.version@'
info:
    version: '@pom.version@'

springfox:
    documentation:
        swagger:
            v2:
                path: /swagger.json
 
server:
     port: 8090
silcam:
     portal:
         ciudado:
              url: http://localhost:3000
         bpm:
              url: http://localhost:8080
spring:
     data:
         mongodb:
              uri: mongodb://localhost:27017/dbgis
     datasource:
         url: jdbc:postgresql://localhost:5432/silcam
         username: silcam
         password: silcam04
     jpa:
         hibernate:
              ddl-auto: validate
         properties:
              hibernate:
                  enable_lazy_load_no_trans: true
     jackson:
         serialization:
              fail-on-empty-beans: false
     mail:
         host: smtp.boaweng.gsnetcloud.corp
         port: 25
         user:
         password:
         protocol: smtp
         tls: false
         auth: false
         from: c3video.no_reply@produban.com
security:
    wso2:
        enabled: false
    basic:
        enabled: false
management:
    security:
        enabled: false
logging:
    level:
        org:
           hibernate:
               SQL: debug
               type:
                   descriptor:
                       sql:
                          BasicBinder: TRACE